### ISSUE TITLE
Factory: Refactor integration tests

### ISSUE THREAD

**Issue by ueco-jb** [WHELP-project/whelp-contracts#38]
Work on branch `factory/more-advanced-testcases`.
https://github.com/WHELP-project/whelp-contracts/compare/main...factory/more-advanced-testcases

Changes that needs to be done:
- rename dependencies to match our own (`dex::`)
- pool configuration - LP share token requires a denom, not token code id
- keep pools in test as smart token - cw20
- remove `placeholder` mentiones, this is part of migration/instantiation we don't need (like `store_placeholder_code` function, test `can_migrate_the_placeholder_to_a_factory_properly`)
- s/pair/pool

**Comment by gangov** [comment]
note to self as per DM's: first make `factory_helper.rs` file compile, comment out the whole `integration.rs` and then continue by uncommenting on test per test basis
