### ISSUE TITLE
CI: Add coverage check

### ISSUE THREAD

**Issue by ueco-jb** [WHELP-project/whelp-contracts#43]

**Comment by gangov** [comment]
we already have code coverage under [Actions](https://github.com/WHELP-project/whelp-contracts/actions/runs/7358375432/workflow) the difference between the one in Whelp and the one in Phoenix is that the Whelp one doesn't upload the results to codecov

**Comment by ueco-jb** [comment]
You can create a profile on codecov.io if you want, I don't see it required. You can see results clearly in actions tab.

**Comment by ueco-jb** [comment]
Coverage is already running.
